### ISSUE TITLE
vulnerability found in axios 0.18.0

### ISSUE THREAD

**Issue by elisherer** [devit-tel/conductor-nodejs-client#11]
Hi,
Great library by the way!
When doing `npm i` we get that a [vulnerability](https://www.npmjs.com/advisories/880) was found in axios 0.18.0.
Can you change the dependency to "^0.18.0" so we can `npm audit fix` it?

**Comment by NV4RE** [comment]
Hello @elisherer,
I bumped axios to 0.19.2, and publish to conductor-client@1.2.0.

If there are any issues or improvement, feel free to make pull request.

Thank you
